name: Publish Docker image
on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_to_registries:
    name: Push Docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.6.0
      - name: Lint Dockerfile rstudio
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "dockerfiles/Dockerfile.rstudio"
      - name: Prepare rstudio
        id: docker_meta_rstudio
        uses: docker/metadata-action@v4.6.0
        with:
          images: hnskde/mongr-dev-rstudio
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push rstudio to Docker Hub
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./dockerfiles/Dockerfile.rstudio
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_rstudio.outputs.tags }}
          labels: ${{ steps.docker_meta_rstudio.outputs.labels }}
          build-args: GH_PAT=${{ secrets.GITHUB_TOKEN }}
